### ISSUE TITLE
The relationship between nsfw_tensorflow and inappropriate_content_detect

### ISSUE THREAD

**Issue by zhuangyanbuaa** [ZixuanLiang/nsfw_tensorflow#2]
Hi Zixuan, 
I used your inappropriate_content_detect model on my private project.
And I just noticed that you have removed that repo and created nsfw_tensorflow.
Could you please tell me more info about the relationship between nsfw_tensorflow and inappropriate_content_detect?
If you have a plan to write your README document soon, just ignore this issue and close it.

Thanks a lot.

**Comment by ZixuanLiang** [comment]
The idea is the same, I move to tensorflow becasue it is easier to deploy the model with tensorflow serving.

**Comment by zhuangyanbuaa** [comment]
Thank you for your answer.
Will you still retain the violence detect model?
The original nsfw model developed by Yahoo can not address graphic violence.

Thanks!
